server:
  port: 8081
  servlet:
    context-path: /
spring:
  servlet:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 1000Mb
  thymeleaf:
    cache : false
    mode: HTML5
  neo4j:
      url: bolt://106.15.182.95:7687
      username: neo4j
      #password: neo4jroot
      password: admin
  resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/